// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3PsMwcU7LYmxrE-9ImfIZshtrDzBPpBI',
    appId: '1:647072265536:web:28049206e0b5edfbb6b6a5',
    messagingSenderId: '647072265536',
    projectId: 'flutterfire-ui-codelab-ce612',
    authDomain: 'flutterfire-ui-codelab-ce612.firebaseapp.com',
    storageBucket: 'flutterfire-ui-codelab-ce612.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAySEWrgtTy2prgwMiXeUJcBjZT0fDvaos',
    appId: '1:647072265536:android:c9a6fd54af7d382db6b6a5',
    messagingSenderId: '647072265536',
    projectId: 'flutterfire-ui-codelab-ce612',
    storageBucket: 'flutterfire-ui-codelab-ce612.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdXzDNfOpCx3c82DAMnF-Y22Bvpba5aw8',
    appId: '1:647072265536:ios:16b0256db98e1ccfb6b6a5',
    messagingSenderId: '647072265536',
    projectId: 'flutterfire-ui-codelab-ce612',
    storageBucket: 'flutterfire-ui-codelab-ce612.appspot.com',
    iosClientId: '647072265536-uest51pdujm5ee561r7pna6bn2n3npun.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterDatabaseFirebase',
  );
}
